/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Util;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;
import clases.Socio;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marin
 */
public class BajaSocio extends javax.swing.JFrame {

    /**
     * Creates new form BajaSocio1
     */
    public BajaSocio() {
        initComponents();
        tabla();//muestra el array de socios en la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Baja de un socio");

        jLabel2.setText("Introduce el id para buscar el socio");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "USUARIO", "NOMBRE", "TELEFONO", "MAIL", "Nº CUENTA", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dar de baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Pinche en la tabla el socio a dar de baja y pulse el botón");

        jButton3.setText("Volver atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(182, 182, 182))))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //botón buscar
        try {
            String id = jTextField1.getText(); // obtener el id del text field
            UUID ID = UUID.fromString(id); //pasarlo a uuid
            Socio socio = Util.buscarSocioId(ID); // devuelve el socio.
            ArrayList socios = Util.getArraySocios(); // array de socios
            int longitud = socios.size(); //longitud del array de socios

            //limpiar la tabla
            limpiaTabla();

            //si buscarSocio devuelve un socio y no null
            if (socio != null) {
                //meter el socio buscado en la tabla
                String nombreColumnas[] = {"USUARIO", "NOMBRE", "TELEFONO", "MAIL", "CUENTA", "ID"};
                Object matriz[][] = new Object[1][6];
                matriz[0][0] = socio.getUsuario();
                matriz[0][1] = socio.getNombre();
                matriz[0][2] = socio.getTelefono();
                matriz[0][3] = socio.getMail();
                matriz[0][4] = socio.getCuenta();
                matriz[0][5] = socio.getId();
                jTable1.setModel(new DefaultTableModel(matriz, nombreColumnas));
            } else {
                JOptionPane.showMessageDialog(this, "El socio con ID: " + ID + "ya ha sido dado de baja", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "El ID introducido no es correcto o no existe un socio con dicho ID", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Botón dar de baja
        String id = jTextField1.getText(); // obtener el id del text field
        UUID ID = UUID.fromString(id); //pasarlo a uuid
        Socio socio = Util.buscarSocioId(ID);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() != -1) {
            modelo.removeRow(jTable1.getSelectedRow()); //socio seleccionado en la tabla
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Dar de baja al usuario?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                Util.bajaSocio(socio);
                JOptionPane.showMessageDialog(this, "El socio con " + ID + "se ha dado de baja", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else if (respuesta == JOptionPane.NO_OPTION) {
                System.out.println("Cancelar");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún socio para darle de baja en la tabla", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        tabla(); //muestra en la tabla los socios que quedan después de dar de baja a uno

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // botón atrás
        this.setVisible(false);
        Recepcionista recepcionista = new Recepcionista();
        recepcionista.setVisible(true);
        recepcionista.setLocationRelativeTo(null);
        recepcionista.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton3ActionPerformed

    //limpia la tabla
    public void limpiaTabla() {
        ArrayList socios = Util.getArraySocios();
        int longitud = socios.size();
        String nombreColumnas[] = {"USUARIO", "NOMBRE", "TELEFONO", "MAIL", "CUENTA", "ID"};
        Object datos[][] = new Object[longitud][6];
        for (int i = 0; i < socios.size(); i++) {
            datos[i][0] = null;
            datos[i][1] = null;
            datos[i][2] = null;
            datos[i][3] = null;
            datos[i][4] = null;
            datos[i][5] = null;
        }
        jTable1.setModel(new DefaultTableModel(datos, nombreColumnas));
    }

    //muestra en la tabla los socios 
    public void tabla() {
        ArrayList socios = Util.getArraySocios();
        int longitud = socios.size();
        String nombreColumnas[] = {"USUARIO", "NOMBRE", "TELEFONO", "MAIL", "CUENTA", "ID"};
        Object datos[][] = new Object[longitud][6];
        for (int i = 0; i < socios.size(); i++) {
            datos[i][0] = Util.getArraySocios().get(i).getUsuario();
            datos[i][1] = Util.getArraySocios().get(i).getNombre();
            datos[i][2] = Util.getArraySocios().get(i).getTelefono();
            datos[i][3] = Util.getArraySocios().get(i).getMail();
            datos[i][4] = Util.getArraySocios().get(i).getCuenta();
            datos[i][5] = Util.getArraySocios().get(i).getId();
        }
        jTable1.setModel(new DefaultTableModel(datos, nombreColumnas));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
