/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Actividad;
import clases.Empleado;
import clases.Monitor;
import clases.Socio;
import clases.Util;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author marin
 */
public class Director extends javax.swing.JFrame {

    /**
     * Creates new form Director1
     */
    public Director() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        alta = new javax.swing.JButton();
        baja = new javax.swing.JButton();
        nuevaActividad = new javax.swing.JButton();
        modificaActividad = new javax.swing.JButton();
        eliminaActividad = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO DIRECTOR");

        alta.setText("ALTA EMPLEADO");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });

        baja.setText("BAJA EMPLEADO");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });

        nuevaActividad.setText("AÑADIR ACTIVIDAD");
        nuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActividadActionPerformed(evt);
            }
        });

        modificaActividad.setText("MODIFICAR ACTIVIDAD");
        modificaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaActividadActionPerformed(evt);
            }
        });

        eliminaActividad.setText("ELIMINAR ACTIVIDAD");
        eliminaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActividadActionPerformed(evt);
            }
        });

        jButton1.setText("MONITORES ACTIVIDADES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ASISTENCIA SOCIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ATRÁS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(alta)
                                        .addGap(18, 18, 18)
                                        .addComponent(nuevaActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(baja)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(eliminaActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(modificaActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alta)
                    .addComponent(nuevaActividad)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baja)
                    .addComponent(modificaActividad)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminaActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        this.setVisible(false);
        AltaEmpleado altaEmpleado = new AltaEmpleado();
        altaEmpleado.setVisible(true);
    }//GEN-LAST:event_altaActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        ArrayList<Empleado> empleados = Util.getArrayEmpleado();
        
        String[] empleados2= new String[empleados.size()];
        for (int i = 0; i < empleados.size(); i++) {
            empleados2[i] = empleados.get(i).getNombre();
        }
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un empleado para dar de baja", "EMPLEADOS", JOptionPane.DEFAULT_OPTION, null, empleados2, empleados2[0]);
        Empleado epl = Util.buscarEmpleado2(resp);
        Util.bajaEmpleado(epl);
        JOptionPane.showMessageDialog(null, "EMPLEADO DADO DE BAJA: " + resp + "   DNI: "+ epl.getDni());


    }//GEN-LAST:event_bajaActionPerformed

    private void nuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActividadActionPerformed
        this.setVisible(false);
        AltaActividad altaActividad = new AltaActividad();
        altaActividad.setVisible(true);
    }//GEN-LAST:event_nuevaActividadActionPerformed

    private void modificaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaActividadActionPerformed
        ArrayList<Actividad> actividades = Util.getArrayActividades();
        ArrayList<Actividad> actividadesMod = Util.getArrayActividadModificada();
        String[] actividades2= new String[actividades.size()];
        for (int i = 0; i < actividades.size(); i++) {
            actividades2[i] = actividades.get(i).getNombre();
        }
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione una actividad para modificarla", "MODIFICAR ACTIVIDAD", JOptionPane.DEFAULT_OPTION, null, actividades2, actividades2[0]);
        Actividad act1 = Util.buscarActividad(resp);
        Util.altaActividadModificada(act1);
        Util.bajaActividad(act1);
        AltaActividad modif = new AltaActividad(act1);
        this.dispose();
        modif.setVisible(true);
    }//GEN-LAST:event_modificaActividadActionPerformed

    private void eliminaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActividadActionPerformed
        ArrayList<Actividad> actividades = Util.getArrayActividades();
        
        String[] actividades2= new String[actividades.size()];
        for (int i = 0; i < actividades.size(); i++) {
            actividades2[i] = actividades.get(i).getNombre();
        }
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione una actividad para eliminarla", "ELIMINAR ACTIVIDAD", JOptionPane.DEFAULT_OPTION, null, actividades2, actividades2[0]);
        Actividad act1 = Util.buscarActividad(resp);
        Util.bajaActividad(act1);
        JOptionPane.showMessageDialog(null, "ELIMINADA");
    }//GEN-LAST:event_eliminaActividadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Empleado> empleados = Util.getArrayEmpleado();
        ArrayList<Monitor> monitores = new ArrayList<Monitor>();
        for (int i = 0; i < empleados.size(); i++) {
            if(empleados.get(i).getTipoEmpleado().equals("Monitor")){
                monitores.add((Monitor) empleados.get(i));
            }
        }
        
        String[] lista = new String[monitores.size()];
        for (int i = 0; i < monitores.size(); i++) {
            lista[i]=monitores.get(i).getNombre()+" - "+monitores.get(i).getTipoActividad().getNombre()+"\n";
        }
        JOptionPane.showMessageDialog(null, lista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<Socio> socios = Util.getArraySocios();
        String[] lista= new String[socios.size()];
        for (int i = 0; i < socios.size(); i++) {
            lista[i] = socios.get(i).getNombre();
        }
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un Socio", "INFORMACIÓN SOCIO", JOptionPane.DEFAULT_OPTION, null, lista, lista[0]);
        String[] cosasSocio = new String[3];
        cosasSocio[0]=resp+"\n";
        Random random = new Random();
        Random random2 = new Random();
        Random random3 = new Random();        
        ArrayList<Actividad> actividades = Util.getArrayActividades();
        int valorDado = random.nextInt(actividades.size())+1; 
        String string = "";
        for (int i = 0; i < valorDado; i++) {
            int randomIndex2 = random.nextInt(actividades.size());
            int randomIndex3 = random.nextInt(31);
            string = string+ actividades.get(randomIndex2).getNombre()+"  -  dia: "+randomIndex3+" de Enero |  ";
        }
        cosasSocio[1]=string;
        cosasSocio[2]= "Tiene acceso a todos los servicios adicionales";
        JOptionPane.showMessageDialog(null, cosasSocio);
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta;
    private javax.swing.JButton baja;
    private javax.swing.JButton eliminaActividad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificaActividad;
    private javax.swing.JButton nuevaActividad;
    // End of variables declaration//GEN-END:variables
}
