/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Actividad;
import clases.Empleado;
import clases.Monitor;
import clases.Socio;
import clases.Util;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

public class SocioVentana extends javax.swing.JFrame {

    private Object bean;
    private String usuario;
   

    public SocioVentana(String usuario) {
        initComponents();
        this.usuario = usuario;
       
        
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solicita = new javax.swing.JButton();
        reserva = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        solicita.setText("SOLICITAR ENTRENADOR");
        solicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitaActionPerformed(evt);
            }
        });

        reserva.setText("RESERVAR ACTIVIDAD");
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });

        jButton2.setText("EVALUAR MONITOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO AL GIMNASIO POPEYE");

        jButton1.setText("ATRÁS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(solicita))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(solicita, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitaActionPerformed
        Socio s1 = new Socio();
        ArrayList<Socio> socios = Util.getArraySocios();
        for (int i = 0; i < socios.size(); i++) {
            if (socios.get(i).getUsuario().equals(this.usuario)) {
                s1 = socios.get(i);
                if (s1.getEntrenador() == null) {
                    ArrayList<Empleado> empleados = Util.getArrayEmpleado();
                    ArrayList<Empleado> entrenadores = new ArrayList<Empleado>();
                    for (int j = 0; j < empleados.size(); j++) {
                        if (empleados.get(j).getTipoEmpleado() == "Entrenador") {
                            entrenadores.add(empleados.get(j));
                        }
                    }
                    Random random = new Random();
                    int value = random.nextInt(entrenadores.size() + 1) + 1;
                    s1.setEntrenador(entrenadores.get(value));
                    JOptionPane.showMessageDialog(null, "Tu nuevo entrenador es: " + s1.getEntrenador().getNombre());
                } else {
                    JOptionPane.showMessageDialog(null, "Tu entrenador es: " + s1.getEntrenador().getNombre());
                }
            }
        }
    }//GEN-LAST:event_solicitaActionPerformed

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed
        Socio s1 = new Socio();
        ArrayList<Socio> socios = Util.getArraySocios();
        for (int i = 0; i < socios.size(); i++) {
            if (socios.get(i).getUsuario().equals(this.usuario)) {
                ArrayList<Actividad> actividades = Util.getArrayActividades();
                String[] actividades2 = {
                    actividades.get(0).getNombre(),
                    actividades.get(1).getNombre(),
                    actividades.get(2).getNombre(),
                    actividades.get(3).getNombre(),
                    actividades.get(4).getNombre()
                };
                String resp = (String) JOptionPane.showInputDialog(null, "Seleccione una actividad", "Actividad", JOptionPane.DEFAULT_OPTION, null, actividades2, actividades.get(0));
                for (int j = 0; j < actividades.size(); j++) {
                    if (actividades.get(j).getNombre().equals(resp)) {
                        JOptionPane.showMessageDialog(null, "RESERVA PARA: " + resp + "    SALA: " + actividades.get(j).getSala() + "    HORARIO: " + actividades.get(j).getHorario());
                    }

                }

            }

        }
    }//GEN-LAST:event_reservaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Socio s1 = new Socio();
        
        ArrayList<Socio> socios = Util.getArraySocios();
      
        for (int i = 0; i < socios.size(); i++) {
            if (socios.get(i).getUsuario().equals(this.usuario)) {
                ArrayList<Actividad> actividades = Util.getArrayActividades();
                String[] actividades2 = {
                    actividades.get(0).getNombre(),
                    actividades.get(1).getNombre(),
                    actividades.get(2).getNombre(),
                    actividades.get(3).getNombre(),
                    actividades.get(4).getNombre()
                };
                String resp = (String) JOptionPane.showInputDialog(null, "Seleccione una actividad para valorar al monitor", "Actividad", JOptionPane.DEFAULT_OPTION, null, actividades2, actividades.get(0));
                String[] notas = {
                    "Muy mal", "Mal", "Regular", "Bien", "Muy bien"
                };
                String resp1 = (String) JOptionPane.showInputDialog(null, "Seleccione una nota", "Notas", JOptionPane.DEFAULT_OPTION, null, notas, notas[4]);
                JOptionPane.showMessageDialog(null, "MONITOR DE " + resp + "      NOTA: " + resp1);
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reserva;
    private javax.swing.JButton solicita;
    // End of variables declaration//GEN-END:variables
}
